---
url:
  type: string
  required: true
  description: The Zabbix frontend URL (e.g. http://zabbix.example.com:8080)
  default: http://localhost:8080
username:
  type: string
  description: Zabbix username (required if api_token not set)
  default: Admin
password:
  type: string
  description: Zabbix password (required if api_token not set)
  default: zabbix
  secret: true
api_token:
  type: string
  description: Zabbix API token (preferred over username/password)
  secret: true
validate_certs:
  type: boolean
  description: Validate HTTPS certificate (honor warnings)
  default: true
timeout:
  type: integer
  description: Connection timeout to Zabbix API
  default: 30
skip_version_check:
  type: boolean
  description: Skip version compatibility check (Use at own risk)
  default: false
